In [11]:
import numpy as np

In [28]:
arr = np.array([[2,4,6,8,10],[1,2,3,4,5],[4,0,6,2,5],[6,6,1,5,3],[7,5,1,3,5],[8,2,4,9,7]])

In [29]:
arr

array([[ 2,  4,  6,  8, 10],
       [ 1,  2,  3,  4,  5],
       [ 4,  0,  6,  2,  5],
       [ 6,  6,  1,  5,  3],
       [ 7,  5,  1,  3,  5],
       [ 8,  2,  4,  9,  7]])

In [25]:
arr[2:4,4] # first entry is for row before comma, second is for columns

array([5, 3])

In [32]:
arr[:,::2] #printing alternative columns

array([[ 2,  6, 10],
       [ 1,  3,  5],
       [ 4,  6,  5],
       [ 6,  1,  3],
       [ 7,  1,  5],
       [ 8,  4,  7]])

# fancy indexing
#boolean indexing